### ISSUE TITLE
Changing LogLevel vs many Requests

### ISSUE THREAD

**Issue by m-shanti** [PawelGerr/Thinktecture.Logging.Configuration#1]
Hi,
I would like to change LogLevel temporarily, depending on some properties of HttpContext.Request.
Thinktecture.Logging gives this functionality.
My application processes many requests. Only 1% of theese requests are requests for which I would like to change LogLevel.
Is LogLevel change separeted between requests? I think that not, so when I'm changing LogLevel it is affecting to other requests which are processed in the same moment.
Am I right?
Thank for response.

**Comment by PawelGerr** [comment]
Hi,
the change of the `LogLevel` happens in the [`LoggerFactory` (v2.2.0, line 152)](https://github.com/aspnet/Logging/blob/release/2.2/src/Microsoft.Extensions.Logging/LoggerFactory.cs) and the `Loggers`. Both, the `LoggerFactory` and the `Loggers` are registered as singletons by default ([LoggingServiceCollectionExtensions.cs, lines 41-42](https://github.com/aspnet/Logging/blob/release/2.2/src/Microsoft.Extensions.Logging/LoggingServiceCollectionExtensions.cs)). 
That's why every change affect all loggers (on all threads/requests).

**Comment by m-shanti** [comment]
Thanks!
